cocognite/urls.py
import notifications.urls
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [

    # BASE URLS -------------------------------------------------------- #
    path('', include('src.wsite.urls', namespace='website')),

    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('s/', include('src.portals.student.urls', namespace='student-portal')),
    path('m/', include('src.portals.moderator.urls', namespace='moderator-portal')),
    path('p/', include('src.portals.parent.urls', namespace='parent-portal')),

    # DEPRECATED ------------------------------------------------------- #
    path('zoom/', include('src.zoom_api.urls', namespace='zoom_api')),

    # NOTIFICATION SERVER ---------------------------------------------- #
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portals/student/urls.py
from django.urls import path
from .views import (
    DashboardView, QuizListView, TeamListView, ZoomMeetingView, QuizEnrollView, QuizLiveView,
    LearningResourceListView, LearningResourceLiveView, LearningResourceResultView, TeamDetailView, TeamDeleteView,
    RelationListView, RelationDetailView, RelationDeleteView, StudentProfileDetailView,

    ActivateZoomAccount,

    LearningResourceLiveQuestionAccessJSON, LearningResourceLiveQuestionSubmitJSON, QuizLiveChoiceSubmitJSON,
    QuizLiveQuestionNextJSON, QuizLiveQuestionAccessJSON, QuizLiveQuestionSubmitJSON, UserExistsJSON
)

app_name = "student-portal"
urlpatterns = [

    path('', DashboardView.as_view(), name='dashboard'),
    path('zoom/<int:quiz>/', ZoomMeetingView.as_view(), name='zoom-meeting'),
    path('zoom/activate/', ActivateZoomAccount.as_view(), name='zoom-activate'),
    path('profile/', StudentProfileDetailView.as_view(), name='profile-detail'),  # UNUSED -->:

    path('team/', TeamListView.as_view(), name='team'),
    path('team/<int:pk>/', TeamDetailView.as_view(), name='team-detail'),  # UNUSED -->:
    path('team/<int:pk>/delete/', TeamDeleteView.as_view(), name='team-delete'),

    path('quiz/', QuizListView.as_view(), name='quiz'),
    path('quiz/<int:pk>/live/', QuizLiveView.as_view(), name='quiz-live'),
    path('quiz/<int:pk>/enroll/', QuizEnrollView.as_view(), name='quiz-enroll'),

    path('learning-resource/', LearningResourceListView.as_view(), name='learning-resource'),
    path('learning-resource/<int:quiz_id>/live/', LearningResourceLiveView.as_view(), name='learning-resource-live'),
    path('learning-resource/<int:quiz_id>/result/', LearningResourceResultView.as_view(),
         name='learning-resource-result'),

    path('relation/', RelationListView.as_view(), name='relation'),
    path('relation/<int:pk>/', RelationDetailView.as_view(), name='relation-detail'),
    path('relation/<int:pk>/delete/', RelationDeleteView.as_view(), name='relation-delete'),

    # -------------------------------------------------------------------------------------------------- JSON RESPONSES
    path('json/learning-resource/live/access/question/<int:question_id>/quiz/<int:quiz_id>/',
         LearningResourceLiveQuestionAccessJSON.as_view(), name='learning-resource-live-access-question-json'),
    path('json/learning-resource/live/submit/question/', LearningResourceLiveQuestionSubmitJSON.as_view(),
         name='learning-resource-live-submit-question-json'),
    path('json/user/<str:username>/exists/', UserExistsJSON.as_view(), name='user-exists-json'),

    path('json/quiz/live/question/submit/', QuizLiveQuestionSubmitJSON.as_view(), name='capi_question_submission'),
    path('json/quiz/live/question/next/', QuizLiveQuestionNextJSON.as_view(), name='capi_next_question'),
    path('json/quiz/<int:quiz_id>/question/<int:question_id>/num/<int:user_id>/skip/<int:skip>/',
         QuizLiveQuestionAccessJSON.as_view(), name='capi_quiz_question_access'
         ),
    path(
        'json/quiz/live/choice/submit/',
        QuizLiveChoiceSubmitJSON.as_view(), name='capi_quiz_choice_submit'
    )
]

src/wsite/urls.py
from django.urls import path
from .views import (
    HomeView, Error404View, LearningListView, QuizListView, PrivacyPolicyView, TermsAndConditionsView
)

app_name = "wsite"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('quizzes/', QuizListView.as_view(), name='quizzes'),
    path('learning-resources/', LearningListView.as_view(), name='learning-resources'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('terms-and-conditions/', TermsAndConditionsView.as_view(), name='terms-and-conditions'),
    path('404/', Error404View.as_view(), name='404'),
]

src/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_resized import ResizedImageField

from cocognite import settings
# from src.application.models import StudentGrade


class User(AbstractUser):
    GENDER_CHOICE = (
        ('m', 'Male'),
        ('f', 'Female'),
        ('o', 'Other'),
    )

    is_student = models.BooleanField(default=False, help_text="This account belongs to student")
    is_moderator = models.BooleanField(default=False, help_text="This account belongs to Moderator/Teacher")
    is_parent = models.BooleanField(default=False, help_text="This account is parental")
    is_completed = models.BooleanField(default=False, help_text="Shows weather the account is associated with any type")

    profile_image = ResizedImageField(
        upload_to='images/profiles/', null=True, blank=True, size=[200, 200], quality=75, force_format='PNG',
        help_text='size of logo must be 100*100 and format must be png image file', crop=['middle', 'center']
    )
    gender = models.CharField(max_length=1, null=True, blank=True, choices=GENDER_CHOICE)
    about = models.TextField(null=True, blank=True, help_text="Tell us something interesting about yourself")
    address = models.TextField(blank=True, null=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Users"

    def __str__(self):
        return self.username

    def delete(self, *args, **kwargs):
        self.profile_image.delete(save=True)
        super(User, self).delete(*args, **kwargs)

    # GET USER PROFILE
    def get_student_profile(self):
        profiles = StudentProfile.objects.filter(user__pk=self.pk, user__is_student=True)
        if not profiles and self.is_student:
            return StudentProfile.objects.create(user=self)
        return profiles.first() if profiles else None


class StudentProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="student-profile+")

    # STUDENT ZOOM
    zoom_account = models.CharField(
        max_length=255, null=True, blank=True,
        help_text="Your official zoom account email address, if you don't have account yet please signup to zoom first"
    )
    zoom_account_verification = models.BooleanField(default=False)
    zoom_user_id = models.CharField(max_length=255, null=True, blank=True)

    # STUDENT STATISTICS
    total_quizzes = models.PositiveIntegerField(default=0)
    passed_quizzes = models.PositiveIntegerField(default=0)
    total_learning = models.PositiveIntegerField(default=0)
    passed_learning = models.PositiveIntegerField(default=0)

    # STUDENT EDUCATION
    grade = models.ForeignKey('application.StudentGrade', on_delete=models.SET_NULL, null=True, blank=True)
    school_name = models.CharField(max_length=255, null=True, blank=True)
    school_email = models.EmailField(null=True, blank=True)
    parent_email = models.EmailField(null=True, blank=True)
    age = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Students Profiles"

    def __str__(self):
        return self.user.username

src/wsite/models.py
from django.db import models
from django_resized import ResizedImageField


class Content(models.Model):
    hero_pre_heading = models.CharField(max_length=1000, default="Play, Learn and Grow")
    hero_heading = models.CharField(max_length=1000, default="Lets Learn Together")
    hero_paragraph_1 = models.TextField(
        default="Human beings are social animals and we have been successful in becoming the most dominant "
                "species, by way of our team effort. Great news is we thrive when we work as a team. "
                "But then why should learning activity be a isolated and single person effort. At CoCognito, "
                "we believe learning need not be a single person effort. Rather it should be a social activity."
    )
    hero_paragraph_2 = models.TextField(
        default="That way it is more engaging, lasting and should be say, more FUN :-) So we have built quizzes "
                "here on variety of subjects that you can practice together with your friend(s). Remember, idea "
                "here is not to compete. But to work together to problem solve a situation. You share ideas, "
                "discuss them, suggest point of views, take suggestions and finally make a decision. Sounds fun, "
                "rite?"
    )
    hero_end_line = models.CharField(max_length=1000, default="Come lets CoCognito !")

    class Meta:
        verbose_name_plural = "Content"

    def __str__(self):
        return self.hero_heading


class Team(models.Model):
    name = models.CharField(max_length=255)
    rank = models.CharField(max_length=255)
    image = ResizedImageField(
        upload_to='website/images/team/', null=True, blank=True, size=[300, 300], quality=75, force_format='PNG',
        help_text='size of logo must be 300*300 and format must be png image file', crop=['middle', 'center']
    )

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Team"

    def __str__(self):
        return self.name


class Testimonial(models.Model):
    TESTIMONIAL_TYPE = (
        ('p', 'Parent'),
        ('s', 'Student'),
        ('m', 'Moderator'),
    )

    name = models.CharField(max_length=255)
    description = models.TextField(default="Description not provided yet.")
    testimonial_type = models.CharField(max_length=1, choices=TESTIMONIAL_TYPE)
    image = ResizedImageField(
        upload_to='website/images/testimonial/', null=True, blank=True, size=[300, 300], quality=75,
        force_format='PNG',
        help_text='size of logo must be 300*300 and format must be png image file', crop=['middle', 'center']
    )

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Testimonials"

    def __str__(self):
        return self.name


class Partner(models.Model):
    name = models.CharField(max_length=255)
    image = ResizedImageField(
        upload_to='website/images/partner/', null=True, blank=True, size=[195, 65], quality=75, force_format='PNG',
        help_text='size of logo must be 195*65 and format must be png image file', crop=['middle', 'center']
    )

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Partners"

    def __str__(self):
        return self.name

src/portals/admins/forms.py
from django.contrib.auth.models import User
from django.forms import *
from django import forms
from src.application.models import (
    Question, QuestionStatement, QuestionImage, QuestionAudio, QuestionChoice, Quiz, QuizQuestion, Article, Team,
    Subject
)


class CSDateTimeInput(forms.DateTimeInput):
    input_type = 'da'


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['id', 'subject', 'question_type', 'age_limit']


class QuestionStatementForm(ModelForm):
    class Meta:
        model = QuestionStatement
        fields = ['statement', 'screen']


class QuestionImageForm(ModelForm):
    class Meta:
        model = QuestionImage
        fields = ['url', 'image']


class QuestionAudioForm(ModelForm):
    class Meta:
        model = QuestionAudio
        fields = ['url', 'audio']


class QuestionChoiceForm(ModelForm):
    class Meta:
        model = QuestionChoice
        fields = ['text', 'is_correct']


''' QUIZ BUILDER VIEWS _______________________________________________________________'''


class QuizForm(ModelForm):
    start_time = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'])
    end_time = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'])

    class Meta:
        model = Quiz
        fields = ['learning_purpose', 'title', 'age_limit', 'players', 'subjects', 'start_time', 'end_time']


class QuizQuestionForm(ModelForm):

    class Meta:
        model = QuizQuestion
        fields = ['submission_control']


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['topic', 'event', 'content', 'content', 'active']


class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

src/wsite/views.py
from django.core.paginator import Paginator
from django.views.generic import TemplateView, ListView

from src.application.models import Quiz
from src.portals.admins.filters import QuizFilter
from src.wsite.models import Content, Testimonial, Team, Partner


class HomeView(TemplateView):
    template_name = 'wsite/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        if Content.objects.all():
            context['content'] = Content.objects.first()
        else:
            context['content'] = Content.objects.create()
        context['dynamic'] = False
        context['testimonials'] = Testimonial.objects.filter(is_active=True)
        context['partners'] = Partner.objects.filter(is_active=True)
        context['team'] = Team.objects.filter(is_active=True)
        context['quizzes'] = Quiz.objects.filter(visible_on_home=True, learning_purpose=False)
        context['learning'] = Quiz.objects.filter(visible_on_home=True, learning_purpose=True)

        return context


class QuizListView(ListView):
    template_name = 'wsite/quiz_list.html'

    def get_queryset(self):
        return Quiz.objects.filter(learning_purpose=False)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(QuizListView, self).get_context_data(**kwargs)
        quiz_filter = QuizFilter(self.request.GET, self.get_queryset())
        context['quiz_filter_form'] = quiz_filter.form

        paginator = Paginator(quiz_filter.qs, 12)
        page_number = self.request.GET.get('page')
        quiz_page_object = paginator.get_page(page_number)

        context['quiz_list'] = quiz_page_object
        return context


class LearningListView(ListView):
    template_name = 'wsite/learning_list.html'

    def get_queryset(self):
        return Quiz.objects.filter(learning_purpose=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(LearningListView, self).get_context_data(**kwargs)
        quiz_filter = QuizFilter(self.request.GET, self.get_queryset())
        context['quiz_filter_form'] = quiz_filter.form

        paginator = Paginator(quiz_filter.qs, 12)
        page_number = self.request.GET.get('page')
        quiz_page_object = paginator.get_page(page_number)

        context['quiz_list'] = quiz_page_object
        return context


class PrivacyPolicyView(TemplateView):
    template_name = 'wsite/policy.html'


class TermsAndConditionsView(TemplateView):
    template_name = 'wsite/terms.html'


class ContactView(TemplateView):
    template_name = 'wsite/contact.html'


class Error404View(TemplateView):
    template_name = 'wsite/404.html'

src/wsite/templates/wsite/contact.html
{% extends 'wsite/base.html' %}
{% load static %}

{% block base_title %}
    Contact Us
{% endblock %}

{% block base_content %}



{% endblock %}

src/wsite/templates/wsite/learning_list.html
{% extends 'wsite/base.html' %}
{% load static %}
{% load custom_tags %}

{% block base_title %}
    Learning Resources
{% endblock %}

{% block base_css_links %}
    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
{% endblock %}

{% block base_content %}

    <div class="page-banner-area item-bg3">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="page-banner-content">
                        <h2>Learn by doing</h2>
                        <ul>
                            <li>
                                <a href="/">Home</a>
                            </li>
                            <li>Learning Resources</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="partner-area ptb-100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">

                    <details>
                        <summary><b>Click To Apply Search Filters</b></summary>

                        <form method="get">
                            <div class=" mb-4">
                                {{ quiz_filter_form }}
                            </div>
                            <div class="">
                                <button class="btn btn-primary" type="submit">
                                    <i class="bx bx-search"></i> Search
                                </button>
                                <a class="btn btn-danger" href="{% url 'website:learning-resources' %}">
                                    <i class="bx bx-brush"></i>
                                </a>
                            </div>
                        </form>
                    </details>
                </div>
            </div>
        </div>
    </div>

    <section class="event-area event-item-two pt-100 pb-70">
        <div class="container-fluid">
            <div class="row">


                {% if quiz_list %}

                    {% for object in quiz_list %}
                        <div class="col-lg-6">
                            <div class="event-box-item">
                                <div class="row align-items-center">
                                    <div class="col-md-3">
                                        <div class="event-image">
                                            {% if not quiz.thumbnail %}
                                                <img class="rounded" src="{% static 'images/no_content.png' %}"
                                                     alt="image">
                                            {% else %}
                                                <img class="rounded" src="{{ quiz.thumbnail.url }}" alt="image">
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="event-content">
                                            <h3>
                                                <a href="#">{{ object.title }}</a>
                                            </h3>
                                            <p>
                                                {{ object.description|truncatechars:120 }}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="event-date">
                                            <p class="mb-0 mt-2">
                                                <a class="btn btn-danger"
                                                   href="{% url 'student-portal:learning-resource-live' object.pk %}">
                                                    Take a Test
                                                </a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}



                    <div class="col-lg-12 col-md-12">
                        <div class="pagination-area">
                            {% if quiz_list.has_previous %}
                                <a href="{% relative_url quiz_list.previous_page_number 'page' request.GET.urlencode %}"
                                   class="prev page-numbers">
                                    <i class='bx bx-chevron-left'></i>
                                </a>
                            {% endif %}
                            <span class="page-numbers current" aria-current="page">{{ quiz_list.number }}</span>
                            {% if quiz_list.has_next %}
                                <a href="{% relative_url quiz_list.next_page_number 'page' request.GET.urlencode %}"
                                   class="next page-numbers">
                                    <i class='bx bx-chevron-right'></i>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                {% else %}
                    <p class="text-center">
                        <b class="text-danger">
                            No Learning Resources available.
                        </b>
                    </p>
                {% endif %}

            </div>
        </div>
    </section>

{% endblock %}


{% block base_internal_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
            integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
{% endblock %}

{% block base_external_js %}

    <script>
        $(document).ready(function () {

            $('input').addClass('form-control');
            $('select').addClass('form-control');

            {#$('#id_grade').val($('#id_grade').find("option:first").text("Select Grade"));#}


            $('#id_start_time').datetimepicker({
                format: 'Y-m-d H:i:s',
            });
            $('#id_end_time').datetimepicker({
                format: 'Y-m-d H:i:s',
            });

        });
    </script>

{% endblock %}

src/wsite/templates/wsite/quiz_list.html
{% extends 'wsite/base.html' %}
{% load static %}
{% load custom_tags %}

{% block base_title %}
    Quizzes
{% endblock %}

{% block base_css_links %}
    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
{% endblock %}

{% block base_content %}
    <div class="page-banner-area item-bg1">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="page-banner-content">
                        <h2>Challenge Yourself Now</h2>
                        <ul>
                            <li>
                                <a href="/">Home</a>
                            </li>
                            <li>Quizzes</li>
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="partner-area ptb-100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">

                    <form method="get">
                        <div class="input-group mb-4">
                            {{ quiz_filter_form }}
                        </div>
                        <div class="">
                            <button class="btn btn-primary" type="submit">
                                <i class="bx bx-search"></i> Search
                            </button>
                            <a class="btn btn-danger" href="{% url 'website:learning-resources' %}">
                                <i class="bx bx-brush"></i>
                            </a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>


    <section class="class-area pt-100 pb-100">
        <div class="container">


            <div class="row">

                {% if quiz_list %}
                    {% for object in quiz_list %}
                        <div class="col-lg-4 col-md-6">
                            <div class="single-class">
                                <div class="class-image">
                                    <a href="#">
                                        {% if not object.thumbnail %}
                                            <img width="550" height="500" src="{% static 'images/no_content.png' %}"
                                                 alt="image">
                                        {% else %}
                                            <img width="550" height="500" src="{{ object.thumbnail.url }}"
                                                 alt="image">
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="class-content">
                                    <div class="price">{{ object.players }}P</div>
                                    <h3>
                                        <a href="#">{{ object.title|truncatechars:50 }}</a>
                                    </h3>
                                    <p>{{ object.description|truncatechars:120 }}</p>
                                    <ul class="class-list">
                                        <li>
                                            <span>Age:</span>
                                            3-{{ object.age_limit }} Year
                                        </li>
                                        <li>
                                            <span>Class:</span>
                                            {{ object.grade }}
                                        </li>
                                        <li>
                                            <span>Time:</span>
                                            <small>{{ object.start_time }} - {{ object.end_time }}</small>
                                        </li>
                                    </ul>
                                    <div class="class-btn">
                                        {% if not request.user.is_authenticated %}
                                            <a href="{% url 'student-portal:quiz-enroll' object.pk %}"
                                               class="default-btn">
                                                Enroll Now
                                            </a>
                                        {% else %}
                                            {% if request.user.is_student %}
                                                <a href="{% url 'account_login' %}" class="default-btn">
                                                    Enroll Now
                                                </a>
                                            {% else %}
                                                <a href="{% url 'account_login' %}" class="default-btn">
                                                    Enroll Now
                                                </a>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                    <div class="col-lg-12 col-md-12">
                        <div class="pagination-area">
                            {% if quiz_list.has_previous %}
                                <a href="{% relative_url quiz_list.previous_page_number 'page' request.GET.urlencode %}"
                                   class="prev page-numbers">
                                    <i class='bx bx-chevron-left'></i>
                                </a>
                            {% endif %}
                            <span class="page-numbers current" aria-current="page">{{ quiz_list.number }}</span>
                            {% if quiz_list.has_next %}
                                <a href="{% relative_url quiz_list.next_page_number 'page' request.GET.urlencode %}"
                                   class="next page-numbers">
                                    <i class='bx bx-chevron-right'></i>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                {% else %}
                    <p class="text-center">
                        <b class="text-danger">
                            No Quizzes available.
                        </b>
                    </p>
                {% endif %}

            </div>
        </div>
        <div class="class-shape">
            <div class="shape-1">
                <img src="{% static 'website/img/class/class-shape-1.png' %}" alt="image">
            </div>
            <div class="shape-2">
                <img src="{% static 'website/img/class/class-shape-2.png' %}" alt="image">
            </div>
        </div>
    </section>

{% endblock %}

{% block base_internal_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
            integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
{% endblock %}

{% block base_external_js %}

    <script>
        $(document).ready(function () {

            $('label').hide();
            $('input').addClass('form-control');
            $('select').addClass('form-control');


            $('#id_start_time').datetimepicker({
                format: 'Y-m-d H:i:s',
            });
            $('#id_end_time').datetimepicker({
                format: 'Y-m-d H:i:s',
            });

        });
    </script>

{% endblock %}