cocognite/urls.py
import notifications.urls
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [

    # BASE URLS -------------------------------------------------------- #
    path('', include('src.wsite.urls', namespace='website')),

    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('s/', include('src.portals.student.urls', namespace='student-portal')),
    path('m/', include('src.portals.moderator.urls', namespace='moderator-portal')),
    path('p/', include('src.portals.parent.urls', namespace='parent-portal')),

    # DEPRECATED ------------------------------------------------------- #
    path('zoom/', include('src.zoom_api.urls', namespace='zoom_api')),

    # NOTIFICATION SERVER ---------------------------------------------- #
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portals/admins/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from src.portals.admins.views import (
    DashboardView,
    ArticleListView, ArticleDeleteView, ArticleCreateView, ArticleUpdateView, ArticleDetailView,
    SubjectListView, SubjectDetailView, SubjectCreateView, SubjectUpdateView, SubjectDeleteView,
    QuizListView, QuizCreateView, QuizUpdateView, QuizDeleteView, QuizDetailView,
    QuestionListView, QuestionCreateView, QuestionDeleteView, QuestionUpdateView,
    RelationListView, RelationCreateView, RelationUpdateView, RelationDeleteView,
    TopicListView, TopicCreateView, TopicUpdateView, TopicDeleteView,
    RelationTypeListView, RelationTypeCreateView, RelationTypeUpdateView, RelationTypeDeleteView,
    StudentGradeListView, StudentGradeCreateView, StudentGradeUpdateView, StudentGradeDeleteView,
    UserListView, UserDetailView,

    QuestionChoiceAddJSON, QuestionChoiceDeleteJSON, QuestionStatementAddJSON, QuestionStatementDeleteJSON,
    QuestionImageCreateView, QuestionImageDeleteView, QuestionAudioCreateView, QuestionAudioDeleteView,

    QuestionStatementStatusUpdateJSON, QuestionChoiceStatusUpdateJSON, QuestionImageStatusUpdateJSON,
    QuestionAudioStatusUpdateJSON, QuestionSubmitStatusUpdateJSON, QuizQuestionAddJSON, QuizQuestionDeleteJSON,

    QuestionTopicAddJSON, QuestionTopicDeleteJSON
)

app_name = "admin-portal"
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('user/', UserListView.as_view(), name='user'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),

    path('article/', ArticleListView.as_view(), name='article'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article-detail'),
    path('add/article/', ArticleCreateView.as_view(), name='article-create'),
    path('update/article/<int:pk>/', ArticleUpdateView.as_view(), name='article-update'),
    path('delete/article/<int:pk>/', ArticleDeleteView.as_view(), name='article-delete'),

    path('relation/', RelationListView.as_view(), name='relation'),
    path('add/relation/', RelationCreateView.as_view(), name='relation-create'),
    path('update/relation/<int:pk>/', RelationUpdateView.as_view(), name='relation-update'),
    path('delete/relation/<int:pk>/', RelationDeleteView.as_view(), name='relation-delete'),

    path('subject/', SubjectListView.as_view(), name='subject'),
    path('subject/<int:pk>/', SubjectDetailView.as_view(), name='subject-detail'),
    path('add/subject/', SubjectCreateView.as_view(), name='subject-create'),
    path('update/subject/<int:pk>/', SubjectUpdateView.as_view(), name='subject-update'),
    path('delete/subject/<int:pk>/', SubjectDeleteView.as_view(), name='subject-delete'),

    path('topic/', TopicListView.as_view(), name='topic'),
    path('add/topic/', TopicCreateView.as_view(), name='topic-create'),
    path('update/topic/<int:pk>/', TopicUpdateView.as_view(), name='topic-update'),
    path('delete/topic/<int:pk>/', TopicDeleteView.as_view(), name='topic-delete'),

    path('relation-type/', RelationTypeListView.as_view(), name='relation-type'),
    path('add/relation-type/', RelationTypeCreateView.as_view(), name='relation-type-create'),
    path('update/relation-type/<int:pk>/', RelationTypeUpdateView.as_view(), name='relation-type-update'),
    path('delete/relation-type/<int:pk>/', RelationTypeDeleteView.as_view(), name='relation-type-delete'),

    path('studentgrade/', StudentGradeListView.as_view(), name='studentgrade'),
    path('add/studentgrade/', StudentGradeCreateView.as_view(), name='studentgrade-create'),
    path('update/studentgrade/<int:pk>/', StudentGradeUpdateView.as_view(), name='studentgrade-update'),
    path('delete/studentgrade/<int:pk>/', StudentGradeDeleteView.as_view(), name='studentgrade-delete'),

    path('quiz/', QuizListView.as_view(), name='quiz'),
    path('add/quiz/', QuizCreateView.as_view(), name='quiz-create'),
    path('quiz/<int:pk>/', QuizDetailView.as_view(), name='quiz-detail'),
    path('update/quiz/<int:pk>/', QuizUpdateView.as_view(), name='quiz-update'),
    path('delete/quiz/<int:pk>/', QuizDeleteView.as_view(), name='quiz-delete'),

    path('question/', QuestionListView.as_view(), name='question'),
    path('question/add/', QuestionCreateView.as_view(), name='question-create'),
    path('question/<int:pk>/change/', QuestionUpdateView.as_view(), name='question-update'),
    path('question/<int:pk>/delete/', QuestionDeleteView.as_view(), name='question-delete'),

    # -------------------------------------------------------------------------------------------------- JSON RESPONSES
    path('json/question_statement/add/', QuestionStatementAddJSON.as_view(), name='question-statement-add-json'),
    path('json/question_choice/add/', QuestionChoiceAddJSON.as_view(), name='question-choice-add-json'),
    path('json/question_statement/<int:pk>/delete/', QuestionStatementDeleteJSON.as_view(),
         name='question-statement-delete-json'),
    path('json/question_choice/<int:pk>/delete/', QuestionChoiceDeleteJSON.as_view(),
         name='question-choice-delete-json'),
    path('json/question_image/<int:question_id>/image/add/', QuestionImageCreateView.as_view(),
         name='question-image-create-json'),
    path('json/question_image/image/<int:pk>/delete/', QuestionImageDeleteView.as_view(),
         name='question-image-delete-json'),
    path('json/question_audio/<int:question_id>/audio/add/', QuestionAudioCreateView.as_view(),
         name='question-audio-create-json'),
    path('json/question_audio/<int:pk>/delete/', QuestionAudioDeleteView.as_view(), name='question-audio-delete-json'),

    path('json/quiz/question/statement/status/<int:pk>/change/', QuestionStatementStatusUpdateJSON.as_view(),
         name='question-statement-status-change-json'),
    path('json/quiz/question/choice/status/<int:pk>/change/', QuestionChoiceStatusUpdateJSON.as_view(),
         name='question-choice-status-change-json'),
    path('json/quiz/question/image/status/<int:pk>/change/', QuestionImageStatusUpdateJSON.as_view(),
         name='question-image-status-change-json'),
    path('json/quiz/question/audio/status/<int:pk>/change/', QuestionAudioStatusUpdateJSON.as_view(),
         name='question-audio-status-change-json'),
    path('json/quiz/question/submission/status/<int:pk>/change/', QuestionSubmitStatusUpdateJSON.as_view(),
         name='question-submission-status-change-json'),

    path('json/quiz/<int:quiz_id>/question/<int:question_id>/add/', QuizQuestionAddJSON.as_view(),
         name='quiz-question-add-json'),
    path('json/quiz/<int:quiz_id>/question/<int:question_id>/delete/', QuizQuestionDeleteJSON.as_view(),
         name='quiz-question-delete-json'),

    path('json/question/<int:question_id>/topic/add/', QuestionTopicAddJSON.as_view(), name='question-topic-add-json'),
    path('json/question/<int:question_id>/topic/delete/', QuestionTopicDeleteJSON.as_view(),
         name='question-topic-delete-json'),

]

src/portals/admins/forms.py
from django.contrib.auth.models import User
from django.forms import *
from django import forms
from src.application.models import (
    Question, QuestionStatement, QuestionImage, QuestionAudio, QuestionChoice, Quiz, QuizQuestion, Article, Team,
    Subject
)


class CSDateTimeInput(forms.DateTimeInput):
    input_type = 'da'


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['id', 'subject', 'question_type', 'age_limit']


class QuestionStatementForm(ModelForm):
    class Meta:
        model = QuestionStatement
        fields = ['statement', 'screen']


class QuestionImageForm(ModelForm):
    class Meta:
        model = QuestionImage
        fields = ['url', 'image']


class QuestionAudioForm(ModelForm):
    class Meta:
        model = QuestionAudio
        fields = ['url', 'audio']


class QuestionChoiceForm(ModelForm):
    class Meta:
        model = QuestionChoice
        fields = ['text', 'is_correct']


''' QUIZ BUILDER VIEWS _______________________________________________________________'''


class QuizForm(ModelForm):
    start_time = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'])
    end_time = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'])

    class Meta:
        model = Quiz
        fields = ['learning_purpose', 'title', 'age_limit', 'players', 'subjects', 'start_time', 'end_time']


class QuizQuestionForm(ModelForm):

    class Meta:
        model = QuizQuestion
        fields = ['submission_control']


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['topic', 'event', 'content', 'content', 'active']


class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

src/portals/admins/templates/admins/article_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Article {% endblock %}
{% block page_heading %} {{ object.topic }} {% endblock %}

{% block content %}


{% endblock %}

src/portals/admins/templates/admins/article_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Update Article{% endblock %}
{% block page_heading %}
    Update Articles
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admin-portal:article' %}"><i class="fa fa-arrow-left"></i> Back to Articles</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/question_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Delete Question {% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <form method="post">{% csrf_token %}
                        <p class="mb-2">Are you sure you want to delete question no:
                            <b class="text-danger">"{{ object.pk }}"</b>
                            ?</p>
                        <input type="submit" class="btn btn-danger" value="Confirm">
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/portals/admins/templates/admins/quiz_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Quiz Builder{% endblock %}

{% block base_links %}
    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
{% endblock %}

{% block page_heading %}
    Quiz Builder
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-7 col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="text-center">
                            {% if not form.instance.thumbnail %}
                                <img src="{% static 'images/no_content.png' %}" class="rounded-circle" height="250"
                                     width="250">
                            {% else %}
                                <img src="{{ form.instance.thumbnail.url }}" class="rounded-circle" height="250"
                                     width="250">
                            {% endif %}
                        </div>
                        <hr>
                        <div class="p-3">
                            <form autocomplete="off" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form | crispy }}
                                <button type="submit" class="btn btn-success"> > Submit</button>
                            </form>
                            <div class="mt-3">
                                <a href="{% url 'admin-portal:quiz' %}"><i class="fa fa-clock"></i> View Quizzes</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock %}

{% block base_internal_scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
            integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {

            let players_div = $('#div_id_players');
            let submission_div = $('#div_id_submission_control');
            let created_by_div = $('#div_id_created_by');
            let start_time_div = $('#div_id_start_time');
            let end_time_div = $('#div_id_end_time');

            created_by_div.hide();
            start_time_div.hide();
            end_time_div.hide();

            check_resource($('#id_learning_purpose').is(':checked'));


            $('#id_learning_purpose').change(function () {
                check_resource(this.checked);
            });

            $('#id_start_time').datetimepicker({
                format: 'Y-m-d H:i:s',
            });
            $('#id_end_time').datetimepicker({
                format: 'Y-m-d H:i:s',
            });


            function check_resource(check) {
                if (check) {
                    players_div.hide();
                    submission_div.hide();
                    start_time_div.hide();
                    end_time_div.hide();
                } else {
                    players_div.show();
                    submission_div.show();
                    start_time_div.show();
                    end_time_div.show();
                }
            }
        });
    </script>
{% endblock %}

src/portals/admins/templates/admins/relation_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Parental Controls {% endblock %}
{% block page_heading %} Parental Controls {% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="row mb-2">
        <div class="col-12">
            <a href="{% url 'admin-portal:relation-create' %}" class="btn btn-primary">
                <i class="fa fa-plus"></i> Add Relation
            </a>
        </div>
    </div>

    <div class="card" id="data_to_print">
        {% if relation_list %}
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Guardian</th>
                            <th scope="col">Child</th>
                            <th scope="col">Created</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% if relation_list %}
                            {% for relation in relation_list %}
                                <tr>
                                    <td>{{ relation.pk }}</td>
                                    <td>
                                        {{ relation.parent.username }}<br>
                                        <small class="text-muted">({{ relation.relation.guardian_relation_name }})</small>
                                    </td>
                                    <td>
                                        {{ relation.child.username }}<br>
                                        <small class="text-muted">({{ relation.relation.student_relation_name }})</small>
                                    </td>
                                    <td>{{ relation.created_on }}</td>
                                    <td>
                                        <b class="text-success">
                                            <i class="fa fa-check-circle"></i> Verified
                                        </b>
                                    </td>
                                    <td>
                                        <b>
                                            <a href="{% url 'admin-portal:relation-update' relation.pk %}">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a href="{% url 'admin-portal:relation-delete' relation.pk %}">
                                                <i class="fa fa-trash text-danger"></i>
                                            </a>
                                        </b>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}

                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <div class="card-body">
                <h5 class="card-title text-danger">No Relations available</h5>
                <p class="card-text mb-0">Hi <b>{{ request.user.username }}</b>!
                    there is no relation available, please add relations
                    <a href="{% url 'admin-portal:relation-type-create' %}">Here</a>.
                </p>
            </div>
        {% endif %}
    </div>


{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}

src/portals/admins/templates/admins/relation_type_create_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Add Relation Type{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                    <div class="mt-3">
                        <a href="{% url 'admin-portal:relation-type' %}"><i class="fa fa-arrow-left"></i> Back to Types</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/relation_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Update Relation{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admin-portal:relation' %}"><i class="fa fa-arrow-left"></i> Back to Relations</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/student_grade_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Grades {% endblock %}
{% block page_heading %}
    Grades
{% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="mb-2">
        <a href="{% url 'admin-portal:studentgrade-create' %}" class="btn btn-primary">
            New Grade
        </a>
    </div>

    <div class="card" id="data_to_print">
        {% if object_list %}
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Created</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for object in object_list %}

                            <tr>
                                <td>{{ object.pk }}</td>
                                <td>{{ object.name }}</td>
                                <td>{{ object.description }}</td>
                                <td>{{ object.created_on }}</td>
                                <td>
                                    {% if object.is_active %}
                                        <i class="fa fa-check text-success"></i>
                                    {% else %}
                                        <i class="fa fa-times text-danger"></i>
                                    {% endif %}
                                </td>
                                <td><a href="{% url 'admin-portal:studentgrade-update' object.pk %}">
                                    <i class="fa fa-edit"></i></a>
                                    <a class="text-danger"
                                       href="{% url 'admin-portal:studentgrade-delete' object.pk %}">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <div class="card-body">
                <h5 class="card-title text-danger">No Relation Types available</h5>
                <p class="card-text mb-0">Hi <b>{{ request.user.username }}</b>!
                    there is no relation type available, please add relation types
                    <a href="{% url 'admin-portal:relation-type-create' %}">Here</a>.
                </p>
            </div>
        {% endif %}
    </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}

src/portals/admins/templates/admins/topic_create_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Add Topic{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admin-portal:topic' %}"><i class="fa fa-arrow-left"></i> Back to Topics</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}