cocognite/urls.py
import notifications.urls
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [

    # BASE URLS -------------------------------------------------------- #
    path('', include('src.wsite.urls', namespace='website')),

    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('s/', include('src.portals.student.urls', namespace='student-portal')),
    path('m/', include('src.portals.moderator.urls', namespace='moderator-portal')),
    path('p/', include('src.portals.parent.urls', namespace='parent-portal')),

    # DEPRECATED ------------------------------------------------------- #
    path('zoom/', include('src.zoom_api.urls', namespace='zoom_api')),

    # NOTIFICATION SERVER ---------------------------------------------- #
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portals/student/urls.py
from django.urls import path
from .views import (
    DashboardView, QuizListView, TeamListView, ZoomMeetingView, QuizEnrollView, QuizLiveView,
    LearningResourceListView, LearningResourceLiveView, LearningResourceResultView, TeamDetailView, TeamDeleteView,
    RelationListView, RelationDetailView, RelationDeleteView, StudentProfileDetailView,

    ActivateZoomAccount,

    LearningResourceLiveQuestionAccessJSON, LearningResourceLiveQuestionSubmitJSON, QuizLiveChoiceSubmitJSON,
    QuizLiveQuestionNextJSON, QuizLiveQuestionAccessJSON, QuizLiveQuestionSubmitJSON, UserExistsJSON
)

app_name = "student-portal"
urlpatterns = [

    path('', DashboardView.as_view(), name='dashboard'),
    path('zoom/<int:quiz>/', ZoomMeetingView.as_view(), name='zoom-meeting'),
    path('zoom/activate/', ActivateZoomAccount.as_view(), name='zoom-activate'),
    path('profile/', StudentProfileDetailView.as_view(), name='profile-detail'),  # UNUSED -->:

    path('team/', TeamListView.as_view(), name='team'),
    path('team/<int:pk>/', TeamDetailView.as_view(), name='team-detail'),  # UNUSED -->:
    path('team/<int:pk>/delete/', TeamDeleteView.as_view(), name='team-delete'),

    path('quiz/', QuizListView.as_view(), name='quiz'),
    path('quiz/<int:pk>/live/', QuizLiveView.as_view(), name='quiz-live'),
    path('quiz/<int:pk>/enroll/', QuizEnrollView.as_view(), name='quiz-enroll'),

    path('learning-resource/', LearningResourceListView.as_view(), name='learning-resource'),
    path('learning-resource/<int:quiz_id>/live/', LearningResourceLiveView.as_view(), name='learning-resource-live'),
    path('learning-resource/<int:quiz_id>/result/', LearningResourceResultView.as_view(),
         name='learning-resource-result'),

    path('relation/', RelationListView.as_view(), name='relation'),
    path('relation/<int:pk>/', RelationDetailView.as_view(), name='relation-detail'),
    path('relation/<int:pk>/delete/', RelationDeleteView.as_view(), name='relation-delete'),

    # -------------------------------------------------------------------------------------------------- JSON RESPONSES
    path('json/learning-resource/live/access/question/<int:question_id>/quiz/<int:quiz_id>/',
         LearningResourceLiveQuestionAccessJSON.as_view(), name='learning-resource-live-access-question-json'),
    path('json/learning-resource/live/submit/question/', LearningResourceLiveQuestionSubmitJSON.as_view(),
         name='learning-resource-live-submit-question-json'),
    path('json/user/<str:username>/exists/', UserExistsJSON.as_view(), name='user-exists-json'),

    path('json/quiz/live/question/submit/', QuizLiveQuestionSubmitJSON.as_view(), name='capi_question_submission'),
    path('json/quiz/live/question/next/', QuizLiveQuestionNextJSON.as_view(), name='capi_next_question'),
    path('json/quiz/<int:quiz_id>/question/<int:question_id>/num/<int:user_id>/skip/<int:skip>/',
         QuizLiveQuestionAccessJSON.as_view(), name='capi_quiz_question_access'
         ),
    path(
        'json/quiz/live/choice/submit/',
        QuizLiveChoiceSubmitJSON.as_view(), name='capi_quiz_choice_submit'
    )
]

src/portals/student/forms.py
from django.forms import ModelForm
from src.application.models import Team


class TeamForm(ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'participants', 'is_active']

src/portals/student/views.py
import json
import statistics

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.generic import ListView, DeleteView, UpdateView
from notifications.signals import notify

from cocognite import settings
from src.accounts.decorators import identification_required, student_required
from src.accounts.models import StudentProfile
from src.application.models import (
    Quiz, Question, QuestionChoice,
    QuizQuestion, Screen, Team, QuizCompleted,
    Attempt, LearningResourceResult, LearningResourceAttempts,
    Relation, QuizMisc,
)
from src.portals.student.bll import question_grading_logic
from src.portals.student.dll import identify_user_in_team
from src.portals.student.forms import TeamForm
from src.portals.student.helpers import generate_signature
from src.zoom_api.views import zoom_create_meeting, zoom_delete_meeting, zoom_create_user

User = get_user_model()

student_decorators = [login_required, identification_required, student_required]
student_nocache_decorators = [login_required, identification_required, student_required, never_cache]

"""  VIEWS ================================================================================= """


@method_decorator(student_decorators, name='dispatch')
class DashboardView(View):

    def get(self, request):
        allow = False

        # ALL_QUIZES
        all_quizes = Quiz.objects.filter(learning_purpose=False).order_by('-start_time')
        my_teams = Team.objects.filter(participants__in=[request.user.id])
        my_quizes = Quiz.objects.filter(id__in=my_teams.values_list('quiz', flat=True))

        total_quizzes = my_quizes.count()
        total_learning = LearningResourceResult.objects.filter(user=request.user).count()
        total_relations = Relation.objects.filter(child=request.user, is_verified_by_child=True).count()

        # AVAILABLE_QUIZES
        available_quizes = Quiz.objects.filter(
            end_time__gte=timezone.now(),
            learning_purpose=False,
            start_time__lte=timezone.now()) \
            .order_by('-start_time')

        completed_by_me = QuizCompleted.objects.filter(user__id=request.user.id)

        # QUIZ ENROLLED
        enrolled_quizes = Quiz.objects \
            .filter(end_time__gt=timezone.now(), learning_purpose=False, id__in=my_quizes.values_list('id', flat=True)) \
            .exclude(id__in=completed_by_me.values_list('quiz', flat=True)).order_by('-start_time')

        # QUIZ SUBMITTED
        completed = Quiz.objects.filter(pk__in=completed_by_me.values_list('quiz', flat=True), learning_purpose=False)
        context = {
            'allow': allow,
            'quizes_all': all_quizes,  # QUIZ=> REQUIRED(current, upcoming)
            'quizes_available': available_quizes,  # QUIZ=> REQUIRED(upcoming, not_enrolled)
            'quizes_enrolled': enrolled_quizes,
            # QUIZ=> REQUIRED(upcoming, not_attempted)[CHECK_MODEL = QuizCompleted]
            'quizes_completed': completed_by_me  # QUIZ=> REQUIRED(Attempted)
        }

        if request.GET.get('quiz'):
            try:
                allow = True
                requested_quiz = Quiz.objects.get(pk=int(request.GET.get('quiz')))

                questions = requested_quiz.questions.all()
                all_teams = Team.objects.filter(quiz=requested_quiz)

                current_team = all_teams.get(participants__in=[request.user])

                list_time_max = []
                list_time_min = []
                list_time_avg = []

                list_total_pass = []
                list_total_correct = []
                list_total_incorrect = []

                list_avg_pass = []
                list_avg_correct = []
                list_avg_incorrect = []

                list_team_pass = []
                list_team_correct = []
                list_team_incorrect = []

                list_time_my_team = []
                for question in questions:
                    _attempts = Attempt.objects.filter(quiz=requested_quiz, question=question).values('team').distinct()
                    list_time_values = []

                    _min_time = -1
                    _avg_time = 0
                    _current_team_time = 0

                    _total_correct = 0
                    _total_incorrect = 0
                    _total_pass = 0

                    _current_team_attempt = 0

                    teams_passed = [x.pk for x in all_teams]

                    for v in _attempts.values('start_time', 'end_time', 'team', 'question', 'successful'):
                        current = (v['end_time'] - v['start_time']).total_seconds()

                        list_time_values.append(current)
                        print(current)
                        print(v['team'])

                        if v['successful']:
                            _total_correct += 1
                        else:
                            _total_incorrect += 1

                        if v['team'] == current_team.pk:
                            _current_team_time = current
                            if v['successful']:
                                _current_team_attempt = 1
                            else:
                                _current_team_attempt = 0

                        if v['team'] in teams_passed:
                            teams_passed.remove(v['team'])

                    print(list_time_values)

                    try:
                        list_time_max.append(round(max(list_time_values), 2))
                    except:
                        list_time_max.append(0)

                    try:
                        list_time_min.append(round(min(list_time_values), 2))
                    except:
                        list_time_min.append(0)

                    try:
                        list_time_avg.append(round(statistics.mean(list_time_values), 2))
                    except:
                        list_time_avg.append(0)

                    list_total_pass.append(round(len(teams_passed), 2))
                    list_total_correct.append(round(_total_correct, 2))
                    list_total_incorrect.append(round(_total_incorrect, 2))
                    list_time_my_team.append(round(_current_team_time, 2))

                    list_avg_pass.append(round(len(teams_passed) / all_teams.count(), 2))
                    list_avg_correct.append(round(_total_correct / all_teams.count(), 2))
                    list_avg_incorrect.append(round(_total_incorrect / all_teams.count(), 2))

                    if current_team.pk in teams_passed:
                        list_team_pass.append(1)
                        list_team_correct.append(0)
                        list_team_incorrect.append(0)
                    else:
                        list_team_pass.append(0)
                        if _current_team_attempt == 1:
                            list_team_correct.append(1)
                            list_team_incorrect.append(0)
                        else:
                            list_team_correct.append(0)
                            list_team_incorrect.append(1)

                chart_1 = {
                    'time_max': list_time_max,
                    'time_min': list_time_min,
                    'time_avg': list_time_avg,
                    'time_my_team': list_time_my_team,
                    'questions': [x for x in range(len(questions))]
                }

                chart_2 = {
                    'total_pass': list_total_pass,
                    'total_correct': list_total_correct,
                    'total_incorrect': list_total_incorrect
                }

                chart_3 = {
                    'avg_pass': list_avg_pass,
                    'avg_correct': list_avg_correct,
                    'avg_incorrect': list_avg_incorrect
                }

                chart_4_5_6 = {
                    'avg_pass': list_avg_pass,
                    'avg_correct': list_avg_correct,
                    'avg_incorrect': list_avg_incorrect,
                    'team_pass': list_team_pass,
                    'team_correct': list_team_correct,
                    'team_incorrect': list_team_incorrect
                }

                context = {
                    'chart_1': chart_1,
                    'chart_2': chart_2,
                    'chart_3': chart_3,
                    'chart_4': chart_4_5_6,
                    'allow': allow,
                    'questions': [count + 1 for count in range(len(questions))],

                    'quizes_all': all_quizes,  # QUIZ=> REQUIRED(current, upcoming)
                    'quizes_available': available_quizes,  # QUIZ=> REQUIRED(upcoming, not_enrolled)
                    'quizes_enrolled': enrolled_quizes,
                    # QUIZ=> REQUIRED(upcoming, not_attempted) [CHECK_MODEL = QuizCompleted]
                    'quizes_completed': completed_by_me  # QUIZ=> REQUIRED(Attempted)
                }

            except Quiz.DoesNotExist:
                allow = False
                messages.error(request, 'Requested quiz does not exists.')
            except Team.DoesNotExist:
                allow = False
                messages.error(request, 'You have not participated in the requested quiz.')

        context['total_relations'] = total_relations
        context['total_quizzes'] = total_quizzes
        context['total_learning'] = total_learning

        return render(request=request, template_name='student/dashboard.html', context=context)

src/portals/student/templates/student/learning_resource_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Learning_resources {% endblock %}

{% block page_heading %}
    Learning Resources
{% endblock %}



{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="card">
        <div class="card-body">

            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#available"><i class="fa fa-pen"></i> Available</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-success" data-toggle="tab" href="#completed"><i class="fa fa-check"></i>
                        Completed</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="available">
                    {% if available_quizes %}
                        <div class="table-responsive py-4">
                            <table class="table table-hover table-bordered table-striped" id="l_available">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Questions</th>
                                    <th>Subjects</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody class="">

                                {% for quiz in available_quizes %}
                                    <tr>
                                        <td>{{ quiz.title }}</td>
                                        <td>{{ quiz.questions.count }}</td>
                                        <td>
                                            {% for subject in quiz.subjects.all %}
                                                <span href=""
                                                      class="badge badge-pill badge-soft-primary">{{ subject.title }}</span>
                                                <br>
                                            {% endfor %}
                                        </td>
                                        <td><a href="{% url 'student-portal:learning-resource-live' quiz.pk %}"><i
                                                class="bx bx-task"></i> Try a tutorial</a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}

                        <div class="card-body">
                            <h5 class="card-title mt-0 text-danger"><i class="fa fa-exclamation-circle"></i> Not Found</h5>
                            <p class="card-text">No learning resources are
                                available now
                                because
                                the admin didn't added yet come back later.
                            </p>
                        </div>
                    {% endif %}
                </div>
                <div class="tab-pane fade show" id="completed">
                    {% if completed_quizes %}
                        <div class="table-responsive py-4">
                            <table class="table table-hover table-bordered table-striped" id="l_result">
                                <thead>
                                <tr>
                                    <th>Quiz</th>
                                    <th>Questions</th>
                                    <th>Marks</th>
                                    <th>Attempts</th>
                                    <th>Subjects</th>
                                    <th>Submitted</th>
                                    <th>Result</th>
                                </tr>
                                </thead>
                                <tbody class="">

                                {% for quiz in completed_quizes %}
                                    <tr>
                                        <td>{{ quiz.quiz.title }}</td>
                                        <td>{{ quiz.quiz.questions.count }}</td>
                                        <td>{{ quiz.obtained }}/{{ quiz.total }}</td>
                                        <td>{{ quiz.attempts }}</td>
                                        <td>
                                            {% for subject in quiz.quiz.subjects.all %}
                                                <span href=""
                                                      class="badge badge-pill badge-soft-primary">{{ subject.title }}</span>
                                                <br>
                                            {% endfor %}
                                        </td>

                                        <td>{{ quiz.created }}</td>
                                        <td>
                                            <b>
                                                <a href="{% url 'student-portal:learning-resource-result' quiz.quiz.id %}"><i
                                                        class="fa fa-eye"></i> View Results</a>
                                            </b>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <div class="card-body">
                            <h5 class="card-title mt-0 text-danger"><i class="fa fa-exclamation-circle"></i> Not Found</h5>
                            <p class="card-text">No learning resources are
                                available now
                                because
                                the admin didn't added yet come back later.</p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block base_internal_scripts %}
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {

            $('table').DataTable();
        });
    </script>
{% endblock %}

src/portals/student/templates/student/relation_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Delete Relation {% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <form method="post">{% csrf_token %}
                        <p class="mb-2">Are you sure your want to remove parental access from
                            <b class="text-danger">"{{ object.parent.username }}"</b> identified as your
                            <b>{{ object.relation.guardian_relation_name }}</b>.
                        </p>
                        <input type="submit" class="btn btn-danger" value="Confirm">
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/portals/student/templates/student/relation_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Parental Control {% endblock %}
{% block page_heading %} Parental Control {% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    {% if relation_list or relation_list_unverified %}
                        <div class="table-responsive">
                            <table class="table table-borderless table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Guardian</th>
                                    <th scope="col">Relation</th>
                                    <th scope="col">Created</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% if relation_list %}
                                    {% for relation in relation_list %}
                                        <tr>
                                            <td>{{ relation.pk }}</td>
                                            <td>
                                                {{ relation.parent.get_full_name }}<br>
                                                <small class="text-muted">({{ relation.parent.username }})</small>
                                            </td>
                                            <td>{{ relation.relation.guardian_relation_name }}</td>
                                            <td>{{ relation.created_on }}</td>
                                            <td>
                                                <b class="text-success">
                                                    <i class="fa fa-check-circle"></i> Verified
                                                </b>
                                            </td>
                                            <td>
                                                <b>
                                                    <a href="{% url 'student-portal:relation-delete' relation.pk %}">
                                                        <i class="fa fa-trash text-danger"></i>
                                                    </a>
                                                </b>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% endif %}

                                {% if relation_list_unverified %}
                                    {% for relation in relation_list_unverified %}
                                        <tr>
                                            <td>{{ relation.pk }}</td>
                                            <td>
                                                {{ relation.parent.get_full_name }}<br>
                                                <small class="text-muted">({{ relation.parent.username }})</small>
                                            </td>
                                            <td>{{ relation.relation.guardian_relation_name }}</td>
                                            <td>{{ relation.created_on }}</td>
                                            <td>
                                                <a href="{% url 'student-portal:relation-detail' relation.pk %}">
                                                    <b class="text-primary">
                                                        <i class="fa fa-exclamation-circle"></i> Not Verified
                                                    </b><br>
                                                    <small>Click here to verify</small>
                                                </a>
                                            </td>
                                            <td>
                                                <b>
                                                    <a href="{% url 'student-portal:relation-delete' relation.pk %}">
                                                        <i class="fa fa-trash text-danger"></i>
                                                    </a>
                                                </b>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}

                        <p class="text-danger">
                            <b>
                                <i class="mdi mdi-exclamation-thick"></i>
                                No parental control access created.
                            </b>
                        </p>

                    {% endif %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

src/portals/student/templates/student/studentprofile_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Student Profile{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-7 col-12">
                <div class="card">
                    <div class="card-header border-bottom bg-white">
                        <p class="mb-0 card-title">
                            Profile Settings
                        </p>
                    </div>
                    <div class="card-body">
                        <div class="p-3">
                            <form autocomplete="off" method="post" action="">
                                {% csrf_token %}
                                {{ form | crispy }}
                                <button type="submit" class="btn btn-success"> > Submit</button>
                            </form>
                            <div class="mt-3">
                                <a href="{% url 'student-portal:dashboard' %}">
                                    <i class="fa fa-clock"></i> Back to Dashboard
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-5 col-12">
                <div class="card">
                    <div class="card-header border-bottom bg-white">
                        <p class="mb-0 card-title">
                            Zoom Account Verification
                        </p>
                    </div>
                    <div class="card-body text-center">
                        {% if request.user.get_student_profile.zoom_user_id %}
                            <div>
                                <h1 class="mb-0 text-success">
                                    <i class="mdi mdi-shield-check"></i><br>
                                </h1>
                                <b class="text-success">(Created)</b>
                                <p class="mb-0"><b>ID:</b> {{ request.user.get_student_profile.zoom_user_id }}</p>
                            </div>
                            <div>

                            </div>
                        {% else %}
                            <div>
                                <h1 class="mb-0 text-danger">
                                    <i class="mdi mdi-shield-alert"></i><br>
                                </h1>
                                <b class="text-danger">(Not Created)</b><br><br>


                                <a href="{% url 'student-portal:zoom-activate' %}">
                                    <b class="btn btn-primary">
                                        <i class="fa fa-link"></i>
                                        Create Zoom Account
                                    </b>
                                </a>
                            </div>
                        {% endif %}

                    </div>
                    <div class="card-footer border-top bg-white">
                        <p class="card-title text-danger">Steps to Validate Your account <small>(optional)</small></p>
                        <ul>
                            {% if request.user.get_student_profile.zoom_user_id %}
                                <li>Your Account is created and ID is <b>{{ request.user.get_student_profile.zoom_user_id }}</b></li>
                            {% else %}
                                <li>Create your account by clicking the button above <b>"Create Zoom Account"</b></li>
                            {% endif %}
                            <li>
                                After creating account, please check your email <b>{{ request.user.email }} </b>to verify.
                            </li>
                            <li>
                                If you get any email from zoom please verify then, if not leave it.
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock %}