cocognite/urls.py
import notifications.urls
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [

    # BASE URLS -------------------------------------------------------- #
    path('', include('src.wsite.urls', namespace='website')),

    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('s/', include('src.portals.student.urls', namespace='student-portal')),
    path('m/', include('src.portals.moderator.urls', namespace='moderator-portal')),
    path('p/', include('src.portals.parent.urls', namespace='parent-portal')),

    # DEPRECATED ------------------------------------------------------- #
    path('zoom/', include('src.zoom_api.urls', namespace='zoom_api')),

    # NOTIFICATION SERVER ---------------------------------------------- #
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portals/moderator/urls.py
from django.urls import path
from .views import (
    DashboardView,

    QuizListView, QuizCreateView, QuizDeleteView, QuizUpdateView, QuizDetailView,
    QuestionListView, QuestionCreateView, QuestionDeleteView, QuestionUpdateView,

    QuestionChoiceAddJSON, QuestionChoiceDeleteJSON, QuestionStatementAddJSON, QuestionStatementDeleteJSON,
    QuestionImageCreateView, QuestionImageDeleteView, QuestionAudioCreateView, QuestionAudioDeleteView,

    QuestionStatementStatusUpdateJSON, QuestionChoiceStatusUpdateJSON, QuestionImageStatusUpdateJSON,
    QuestionAudioStatusUpdateJSON, QuestionSubmitStatusUpdateJSON, QuizQuestionAddJSON, QuizQuestionDeleteJSON,

    QuestionTopicAddJSON, QuestionTopicDeleteJSON
)

app_name = "moderator-portal"
urlpatterns = [

    path('', DashboardView.as_view(), name='dashboard'),

    path('quiz/', QuizListView.as_view(), name='quiz'),
    path('add/quiz/', QuizCreateView.as_view(), name='quiz-create'),
    path('quiz/<int:pk>/', QuizDetailView.as_view(), name='quiz-detail'),
    path('update/quiz/<int:pk>/', QuizUpdateView.as_view(), name='quiz-update'),
    path('delete/quiz/<int:pk>/', QuizDeleteView.as_view(), name='quiz-delete'),

    path('question/', QuestionListView.as_view(), name='question'),
    path('question/add/', QuestionCreateView.as_view(), name='question-create'),
    path('question/<int:pk>/change/', QuestionUpdateView.as_view(), name='question-update'),
    path('question/<int:pk>/delete/', QuestionDeleteView.as_view(), name='question-delete'),

    # -------------------------------------------------------------------------------------------------- JSON RESPONSES
    path('json/question_statement/add/', QuestionStatementAddJSON.as_view(), name='question-statement-add-json'),
    path('json/question_choice/add/', QuestionChoiceAddJSON.as_view(), name='question-choice-add-json'),
    path('json/question_statement/<int:pk>/delete/', QuestionStatementDeleteJSON.as_view(),
         name='question-statement-delete-json'),
    path('json/question_choice/<int:pk>/delete/', QuestionChoiceDeleteJSON.as_view(),
         name='question-choice-delete-json'),
    path('json/question_image/<int:question_id>/image/add/', QuestionImageCreateView.as_view(),
         name='question-image-create-json'),
    path('json/question_image/image/<int:pk>/delete/', QuestionImageDeleteView.as_view(),
         name='question-image-delete-json'),
    path('json/question_audio/<int:question_id>/audio/add/', QuestionAudioCreateView.as_view(),
         name='question-audio-create-json'),
    path('json/question_audio/<int:pk>/delete/', QuestionAudioDeleteView.as_view(), name='question-audio-delete-json'),

    path('json/quiz/question/statement/status/<int:pk>/change/', QuestionStatementStatusUpdateJSON.as_view(),
         name='question-statement-status-change-json'),
    path('json/quiz/question/choice/status/<int:pk>/change/', QuestionChoiceStatusUpdateJSON.as_view(),
         name='question-choice-status-change-json'),
    path('json/quiz/question/image/status/<int:pk>/change/', QuestionImageStatusUpdateJSON.as_view(),
         name='question-image-status-change-json'),
    path('json/quiz/question/audio/status/<int:pk>/change/', QuestionAudioStatusUpdateJSON.as_view(),
         name='question-audio-status-change-json'),
    path('json/quiz/question/submission/status/<int:pk>/change/', QuestionSubmitStatusUpdateJSON.as_view(),
         name='question-submission-status-change-json'),
    path('json/quiz/<int:quiz_id>/question/<int:question_id>/add/', QuizQuestionAddJSON.as_view(),
         name='quiz-question-add-json'),
    path('json/quiz/<int:quiz_id>/question/<int:question_id>/delete/', QuizQuestionDeleteJSON.as_view(),
         name='quiz-question-delete-json'),

    path('json/question/<int:question_id>/topic/add/', QuestionTopicAddJSON.as_view(), name='question-topic-add-json'),
    path('json/question/<int:question_id>/topic/delete/', QuestionTopicDeleteJSON.as_view(),
         name='question-topic-delete-json'),

]

src/portals/admins/forms.py
from django.contrib.auth.models import User
from django.forms import *
from django import forms
from src.application.models import (
    Question, QuestionStatement, QuestionImage, QuestionAudio, QuestionChoice, Quiz, QuizQuestion, Article, Team,
    Subject
)


class CSDateTimeInput(forms.DateTimeInput):
    input_type = 'da'


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['id', 'subject', 'question_type', 'age_limit']


class QuestionStatementForm(ModelForm):
    class Meta:
        model = QuestionStatement
        fields = ['statement', 'screen']


class QuestionImageForm(ModelForm):
    class Meta:
        model = QuestionImage
        fields = ['url', 'image']


class QuestionAudioForm(ModelForm):
    class Meta:
        model = QuestionAudio
        fields = ['url', 'audio']


class QuestionChoiceForm(ModelForm):
    class Meta:
        model = QuestionChoice
        fields = ['text', 'is_correct']


''' QUIZ BUILDER VIEWS _______________________________________________________________'''


class QuizForm(ModelForm):
    start_time = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'])
    end_time = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'])

    class Meta:
        model = Quiz
        fields = ['learning_purpose', 'title', 'age_limit', 'players', 'subjects', 'start_time', 'end_time']


class QuizQuestionForm(ModelForm):

    class Meta:
        model = QuizQuestion
        fields = ['submission_control']


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['topic', 'event', 'content', 'content', 'active']


class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

src/portals/moderator/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.generic import (
    ListView, UpdateView, DeleteView, CreateView, DetailView,
    TemplateView)

from src.accounts.decorators import moderator_required, identification_required
from src.application.models import (
    Quiz, QuizQuestion, Question, ChoiceVisibility, StatementVisibility, ImageVisibility,
    AudioVisibility,
    Subject, QuestionStatement, QuestionChoice, QuestionAudio, QuestionImage, Screen, Topic, StudentGrade)
from src.portals.admins.dll import QuestionDS
from src.portals.admins.forms import QuizQuestionForm, QuestionAudioForm, QuestionImageForm

moderator_decorators = [moderator_required, identification_required]
moderator_nocache_decorators = [moderator_required, identification_required, never_cache]


@method_decorator(moderator_decorators, name='dispatch')
class DashboardView(TemplateView):
    template_name = 'moderator/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        questions = Question.objects.filter(created_by=self.request.user)
        quizzes = Quiz.objects.filter(created_by=self.request.user)

        context['questions'] = questions[:20]
        context['questions_all'] = questions.count()
        context['quizzes'] = quizzes[:20]
        context['single_all'] = quizzes.filter(players='1', learning_purpose=False).count()
        context['learning_all'] = quizzes.filter(learning_purpose=True).count()
        context['team_all'] = quizzes.filter(learning_purpose=False).exclude(players='1').count()
        return context


""" QUIZ """
@method_decorator(moderator_decorators, name='dispatch')
class QuizListView(ListView):
    models = Quiz
    template_name = 'moderator/quiz_list.html'

    def get_queryset(self):
        return Quiz.objects.filter(created_by=self.request.user)


@method_decorator(moderator_decorators, name='dispatch')
class QuizCreateView(CreateView):
    models = Quiz
    queryset = Quiz.objects.all()
    fields = [
        'thumbnail', 'learning_purpose', 'title', 'description', 'age_limit',
        'subjects', 'grade', 'players', 'start_time', 'end_time',
        'visible_on_home'
    ]
    template_name = 'moderator/quiz_create_form.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        if form.instance.learning_purpose:
            form.instance.start_time = timezone.now()
            form.instance.end_time = timezone.now()
        return super(QuizCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('moderator-portal:quiz-detail', kwargs={'pk': self.object.pk})


@method_decorator(moderator_decorators, name='dispatch')
class QuizUpdateView(UpdateView):
    models = Quiz
    fields = [
        'thumbnail', 'learning_purpose', 'title', 'description', 'age_limit', 'subjects',
        'grade', 'players', 'start_time', 'end_time', 'visible_on_home'
    ]
    template_name = 'moderator/quiz_update_form.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Quiz.objects.filter(created_by=self.request.user), pk=self.kwargs['pk'])

    def get_success_url(self):
        return reverse('moderator-portal:quiz-detail', kwargs={'pk': self.object.pk})


@method_decorator(moderator_decorators, name='dispatch')
class QuizDeleteView(DeleteView):
    models = Quiz
    template_name = 'moderator/quiz_delete.html'
    success_url = reverse_lazy('moderator-portal:quiz')

    def get_object(self, queryset=None):
        return get_object_or_404(Quiz.objects.filter(created_by=self.request.user), pk=self.kwargs['pk'])


@method_decorator(moderator_nocache_decorators, name='dispatch')
class QuizDetailView(DetailView):
    template_name = 'moderator/quiz_detail.html'
    model = Quiz

    def get_object(self, queryset=None):
        return get_object_or_404(Quiz.objects.filter(created_by=self.request.user), pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(QuizDetailView, self).get_context_data(**kwargs)
        quiz = self.get_object()

        quiz_questions = QuizQuestion.objects.filter(quiz=quiz)
        questions = Question.objects.filter(subject__in=quiz.subjects.all(), age_limit__lte=quiz.age_limit)
        total = questions.count()
        questions = questions.exclude(id__in=quiz_questions.values_list('question__id', flat=True))

        questionsDS = []
        for quiz_question in quiz_questions:

            question_exists = False
            if quiz_question.question in quiz.questions.all():
                question_exists = True

            questionDS = QuestionDS(
                id=quiz_question.pk, question_id=quiz_question.question.pk, question_exists=question_exists,
                level=quiz_question.question.level, subject=quiz_question.question.subject,
                question_type=quiz_question.question.question_type, age_limit=quiz_question.question.age_limit,
                submission_control=quiz_question.submission_control
            )

            for choice_v in ChoiceVisibility.objects.filter(
                    quiz_question=quiz_question, quiz_question__quiz=quiz):
                questionDS.add_choice(
                    id=choice_v.id, description=choice_v.choice.text, is_correct=choice_v.choice.is_correct,
                    screen1=choice_v.screen_1, screen2=choice_v.screen_2, screen3=choice_v.screen_3
                )

            for statement_v in StatementVisibility.objects.filter(
                    quiz_question=quiz_question, quiz_question__quiz=quiz):
                questionDS.add_statment(
                    id=statement_v.id, description=statement_v.statement.statement,
                    screen1=statement_v.screen_1, screen2=statement_v.screen_2, screen3=statement_v.screen_3
                )

            for image_v in ImageVisibility.objects.filter(
                    quiz_question=quiz_question, quiz_question__quiz=quiz):
                if image_v.image.image:
                    questionDS.add_image(
                        id=image_v.id, url=image_v.image.url, image=image_v.image.image.url,
                        screen1=image_v.screen_1, screen2=image_v.screen_2, screen3=image_v.screen_3
                    )
                else:
                    questionDS.add_image(
                        id=image_v.id, url=image_v.image.url, image=None,
                        screen1=image_v.screen_1, screen2=image_v.screen_2, screen3=image_v.screen_3
                    )

            for audio_v in AudioVisibility.objects.filter(
                    quiz_question=quiz_question, quiz_question__quiz=quiz):
                if audio_v.audio.audio:
                    questionDS.add_audio(
                        id=audio_v.id, url=audio_v.audio.url, audio=audio_v.audio.audio.url,
                        screen1=audio_v.screen_1, screen2=audio_v.screen_2, screen3=audio_v.screen_3
                    )
                else:
                    questionDS.add_audio(
                        id=audio_v.id, url=audio_v.audio.url, audio=None,
                        screen1=audio_v.screen_1, screen2=audio_v.screen_2, screen3=audio_v.screen_3
                    )

            questionsDS.append(questionDS)

        context = {
            'questionDS': questionsDS,
            'questions': questions,
            'subjects': quiz.subjects.all(),
            'form': QuizQuestionForm(instance=QuizQuestion.objects.first()),
            'quiz_id': quiz.pk,
            'quiz_title': quiz.title,
            'total': total,
            'selected': quiz.questions.count(),
            'remaining': questions.count(),
            'players': quiz.players,
        }

        return context


""" QUESTION """


@method_decorator(moderator_decorators, name='dispatch')
class QuestionListView(ListView):
    models = Question
    template_name = 'moderator/question_list.html'

    def get_queryset(self):
        return Question.objects.filter(created_by=self.request.user)


@method_decorator(moderator_decorators, name='dispatch')
class QuestionDeleteView(DeleteView):
    models = Question
    template_name = 'moderator/question_delete.html'
    success_url = reverse_lazy('moderator-portal:question')

    def get_object(self, queryset=None):
        return get_object_or_404(Question.objects.filter(
            created_by=self.request.user), pk=self.kwargs.get('pk'))


@method_decorator(moderator_decorators, name='dispatch')
class QuestionCreateView(View):

    def get(self, request):
        question_subjects = Subject.objects.all()
        question_grade = StudentGrade.objects.all()
        context = {
            'subjects': question_subjects,
            'grades': question_grade,
            'topics': Topic.objects.all()
        }
        return render(request=request, template_name='moderator/question_add_form.html', context=context)

    def post(self, request):
        topics = request.POST.getlist('topics[]')
        corrects = request.POST.getlist('corrects[]')
        options = request.POST.getlist('options[]')

        # 1: CREATE QUESTION
        question = Question.objects.create(
            age_limit=request.POST['age'], grade=StudentGrade.objects.get(pk=request.POST['grade_id']),
            subject=Subject.objects.get(pk=request.POST['subject_id']), created_by=request.user
        )

        # 2: CREATE STATEMENTS
        for statement in request.POST.getlist('statements[]'):
            QuestionStatement.objects.create(

src/portals/moderator/templates/moderator/question_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Questions {% endblock %}
{% block page_heading %} Questions {% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}


{% block content %}

    <div class="mb-2">
        <a href="{% url 'moderator-portal:question-create' %}" class="btn btn-primary">
            Add Question
        </a>
    </div>

    <div class="card">
        <div class="card-body">
            {% if question_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>SNO</th>
                            <th>Statement</th>
                            <th>Choices</th>
                            <th>Subject</th>
                            <th>Age</th>
                            <th>created at</th>
                            <th>Level</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for question in question_list %}
                            <tr>
                                <td>{{ question.pk }}</td>
                                <td class="text-wrap">{{ question.get_statement|truncatechars:'50' }}</td>
                                <td>{{ question.choices_control }}</td>
                                <td>{{ question.subject }}</td>
                                <td>{{ question.age_limit }}</td>
                                <td>{{ question.created_at }}</td>
                                <td>
                                    {% if question.level == 'e' %}
                                        <i class="fa fa-star text-warning"></i>
                                        <i class="fa fa-star text-secondary"></i>
                                        <i class="fa fa-star text-secondary"></i>
                                    {% elif question.level == 'n' %}
                                        <i class="fa fa-star text-warning"></i>
                                        <i class="fa fa-star text-warning"></i>
                                        <i class="fa fa-star text-secondary"></i>
                                    {% else %}
                                        <i class="fa fa-star text-warning"></i>
                                        <i class="fa fa-star text-warning"></i>
                                        <i class="fa fa-star text-warning"></i>
                                    {% endif %}
                                </td>
                                <td><a href="{% url 'moderator-portal:question-update' question.pk %}">
                                    <i class="fa fa-edit"></i></a>

                                    {#                                    <a href="{% url 'application:update_question' question.pk %}">#}
                                    {#                                        <i class="fa fa-edit"></i> Edit</a>#}
                                    {#                                    #}
                                    <a class="text-danger"
                                       href="{% url 'moderator-portal:question-delete' question.pk %}">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            {% else %}
                <h5 class="card-title text-danger">No Questions available</h5>
                <p class="card-text"><b>{{ request.user.username }}</b>! there is no question
                available,
                include some questions to attract your users, First add Quiz <a
                    href="{% url 'moderator-portal:quiz-create' %}">Here</a> then you can add questions
                <a href="{% url 'moderator-portal:question-create' %}">Here</a>.
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}

src/portals/moderator/templates/moderator/quiz_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Quizzes {% endblock %}
{% block page_heading %} Quizzes {% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="mb-2">
        <a href="{% url 'moderator-portal:quiz-create' %}" class="btn btn-primary">
            Add Quiz
        </a>
    </div>

    <div class="card">
        <div class="card-body">
            {% if quiz_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Players</th>
                            <th>Subjects</th>
                            <th>Questions</th>
                            <th>Time</th>
                            <th>Type</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for quiz in quiz_list %}
                            <tr>
                                <td>{{ quiz.pk }}</td>
                                <td>{{ quiz.title }}</td>
                                <td>{{ quiz.players }}</td>
                                <td>{{ quiz.subjects.count }}</td>
                                <td>{{ quiz.questions.count }}</td>
                                <td>
                                    <i class="fa fa-play-circle"></i> {{ quiz.start_time }}<br>
                                    <i class="fa fa-stop-circle"></i> {{ quiz.end_time }}<br>
                                </td>
                                <td>

                                    {% if quiz.learning_purpose %}
                                        <b class="text-primary">Practice</b>
                                    {% else %}
                                        <b class="text-success">Quiz</b>
                                    {% endif %}

                                </td>
                                <td><a href="{% url 'moderator-portal:quiz-detail' quiz.pk %}">
                                    <i class="fa fa-eye"></i></a>
                                    <a href="{% url 'moderator-portal:quiz-update' quiz.pk %}">
                                        <i class="fa fa-edit"></i></a>
                                    <a class="text-danger" href="{% url 'moderator-portal:quiz-delete' quiz.pk %}">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="card-body">
                    <h5 class="card-title text-danger">No Quizes available</h5>
                    <p class="card-text"><b>{{ request.user.username }}</b>! there is no quiz available,
                        include some quizes to attract your users, You can add quizes
                        <a href="{% url 'moderator-portal:quiz-create' %}">Here</a>.
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}